name: Check Style

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout module
      uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Check style
      uses: wilkware/action-ips-style@main